"""Add preferences table

Revision ID: 6bd8b7e6142b
Revises: 
Create Date: 2025-02-07 20:23:22.130445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd8b7e6142b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference')
    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('diet', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.String(length=200), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('dietary')
        batch_op.drop_column('cooking_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooking_time', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('dietary', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('allergies')
        batch_op.drop_column('diet')
        batch_op.drop_column('max_time')

    op.create_table('preference',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('preference_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cooking_time', sa.INTEGER(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=10), nullable=True),
    sa.Column('allergies', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
